# Site settings
title: Luis Crespo
email: luiscrisf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Luis Crespo is a full-stack software engineering professional.
  Passionate for software development in general, but especialized in web
  front-end engineering, using state of the art techs, frameworks and patterns.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://luisincrespo.github.io" # the base hostname & protocol for your site
github_username:  luisincrespo
twitter_username: luisincrespo
linkedin_profile: https://ve.linkedin.com/in/luisincrespo
google_profile: https://plus.google.com/u/0/+LuisCrespoFalco

# Build settings
markdown: kramdown

# Defaults for Front Matter
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
